### ISSUE TITLE
Return code from --version should probably be 0

### ISSUE THREAD

**Issue by beewoolie** [ndilieto/uacme#50]
# uacme --version 2> /dev/null && echo "OK" || echo "Nope"

This is a common way to determine whether or not the program is present.  However, uacme returns a failure code, non-zero, from this command and from uacme --help.

**Comment by ndilieto** [comment]
By design uacme returns 0 only on successful certificate renewal, 1 when the certificate is still current and 2 in all other cases. I am not going to change this. If you need to check if uacme is present you are much better off using the 'which' command, that returns 0 if all specified commands are found and executable.
