### ISSUE TITLE
Set CA bundle to verify ACME Server against

### ISSUE THREAD

**Issue by uedvt359** [ndilieto/uacme#65]
I need to issue a certificate from an ACME server whose TLS certificate is not in `/etc/ssl/certs/ca-certificates.crt`, the default CABundle of Alpine Linux. This results in this error message:

    uacme: curl_get: GET https://acme.***:8443/directory failed: SSL peer certificate or SSH remote key was not OK 

I tried setting CURL_CA_BUNDLE, but that didn't work. Is there a way to set which CA Bundle `curl_get` uses? For reasons I don't want to get into adding the CA to the default bundle isn't desired.

**Comment by ndilieto** [comment]
That won't work because unlike curl, the command line utility, unfortunately libcurl only supports a very limited set of environment variables, as described at https://curl.se/libcurl/c/libcurl-env.html 

You can always patch the uacme source, adding a call to curl_easy_setopt with CURLOPT_CAINFO, see https://curl.se/libcurl/c/CURLOPT_CAINFO.html

**Comment by ndilieto** [comment]
FYI, the latest release (1.7.6) supports the UACME_CAINFO and UACME_CAPATH environment variables, which translate to CURLOPT_CAINFO and CURLOPT_CAPATH.
